name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Release
        path: app/build/outputs/apk/release/
